import { ReactNode, useState } from "react"
import { Text, View } from "react-native"
import Svg, {
	Circle,
	G,
	Line,
	Polyline,
	Text as SVGText,
} from "react-native-svg"
import { computeAxes } from "../utils/linechart/compute-axes"
import { computeDataPoints } from "../utils/linechart/compute-datapoints"
import {
	calculateGridValues,
	computeGrid,
} from "../utils/linechart/compute-grid"
import { calculateTicks } from "../utils/linechart/compute-linechart"
import { msToDate } from "../utils/linechart/helpers"
import { ChartAxes } from "./chart-axes"
import { ChartGrid } from "./chart-grid"

export type LabelData = Record<string, string>
type LineChartProps = {
	data: { x: number | Date; y: number }[]
	xTickCountTarget?: number // 2- 20,
	yTickCountTarget?: number // 2- 20,
	dateTickInterval?: "day" | "week" | "month" | "year"
	labelInterval?: number
	gridStroke?: string
	gridStrokeX?: string
	gridStrokeY?: string
	gridStrokeWidth: number
	gridOpacity?: string | number
	showXLabels?: boolean
	showYLabels?: "left" | "right" | "none"
	labelProp?: (
		label: LabelData,
		x: number,
		y: number,
		fontSize: number,
	) => React.ReactNode
}

/**
 *
 * @param TickCountTarget Number of ticks the chart tries to generate on the axis (does not work with dates)
 *
 */
const LineChart = ({
	data,
	xTickCountTarget,
	yTickCountTarget,
	labelInterval,
	dateTickInterval,
	gridStroke,
	gridStrokeX,
	gridStrokeY,
	gridStrokeWidth,
	gridOpacity,
	showXLabels,
	showYLabels,
	labelProp,
}: LineChartProps) => {
	//TODO: Vertical, horizontal lines + full grid functionality
	// X and Y axis lines (optional)
	// Display X and Y axis values (optional)

	//How many X & Y lines to generate?
	//Lines are generated by spacing: roundUp((max value - min value) / array.length - 1)
	//Spacing is calculated by the chartWidth / aforementioned value and making the step value "nice" e.g. 5 or 10

	//Component height and width are determined by the parent container
	//The component fills the container
	//Size is determined by parent container flex and width values.
	const safeTickCountTargetX = Math.min(Math.max(xTickCountTarget ?? 3, 2), 20)
	const safeTickCountTargetY = Math.min(Math.max(yTickCountTarget ?? 3, 2), 20)
	const chartAxisValues = calculateGridValues(data)
	const safeGridStroke = gridStroke ?? "black"
	const safeGridOpacity = gridOpacity ?? "50%"
	const safeGridStrokeWidth = gridStrokeWidth ?? 10
	const safeShowXLabel = showXLabels !== false
	const safeYLabelPos = showYLabels ?? "left"

	const safeLabelInterval =
		labelInterval && labelInterval > 0 ? labelInterval : 1
	const safeDateTickInterval = dateTickInterval ?? "week"
	const [dimensions, setDimensions] = useState({ width: 0, height: 0 })

	const xAxisVal = calculateTicks(
		safeTickCountTargetX,
		chartAxisValues.minX,
		chartAxisValues.maxX,
		chartAxisValues.isDate,
		safeDateTickInterval,
	)
	const yAxisVal = calculateTicks(
		safeTickCountTargetY,
		chartAxisValues.minY,
		chartAxisValues.maxY,
		false,
	)

	const labelFontSize = (10 / 225) * dimensions.height
	const scalableGridStrokeWidth =
		(safeGridStrokeWidth / 1000) * dimensions.height
	const paddingX = (dimensions.width * 0.1 + labelFontSize) * 1.1
	const paddingY = (dimensions.height * 0.1 + labelFontSize) * 1.5

	const chartWidth = dimensions.width - paddingX * 2
	const chartHeight = dimensions.height - paddingY * 2

	//TODO: Change to xGridData and yGridData
	const { xLineData, yLineData } = computeGrid(
		xAxisVal,
		yAxisVal,
		paddingX,
		paddingY,
		chartHeight,
		chartWidth,
		safeLabelInterval,
		labelFontSize,
		safeShowXLabel,
		safeYLabelPos,
	)

	const { xAxisData, yAxisData } = computeAxes(
		xAxisVal,
		yAxisVal,
		paddingX,
		paddingY,
		chartHeight,
		chartWidth,
		safeLabelInterval,
		labelFontSize,
		safeShowXLabel,
		safeYLabelPos,
	)

	const dataPoints = computeDataPoints(
		data,
		paddingX,
		paddingY,
		chartWidth,
		chartHeight,
		xAxisVal,
		yAxisVal,
	)

	let polyLineStr = ""
	dataPoints.forEach((point, i) => {
		const x = point.cx
		const y = point.cy
		polyLineStr = polyLineStr + `${x},${y} `
	})

	return (
		<View
			style={{ flex: 1 }}
			onLayout={(e) => setDimensions(e.nativeEvent.layout)}
		>
			<Svg
				width={dimensions.width}
				height={dimensions.height}
				style={{ flex: 1 }}
			>
				<ChartGrid
					xLineData={xLineData}
					yLineData={yLineData}
					isDate={chartAxisValues.isDate}
					labelFontSize={labelFontSize}
					labelComponent={labelProp}
					stroke={safeGridStroke}
					xStroke={gridStrokeX}
					yStroke={gridStrokeY}
					strokeWidth={scalableGridStrokeWidth}
					opacity={safeGridOpacity}
				/>
				<ChartAxes
					paddingX={paddingX}
					paddingY={paddingY}
					chartHeight={chartHeight}
					chartWidth={chartWidth}
					xAxisData={xAxisData}
					yAxisData={yAxisData}
					fontSize={labelFontSize}
					isDate={chartAxisValues.isDate}
					yLabelPos={safeYLabelPos}
					labelComponent={labelProp}
				/>

				{dataPoints.map((point, i) => (
					<Circle cx={point.cx} cy={point.cy} key={i} r={2} />
				))}
				<Polyline points={polyLineStr} fill="none" stroke="black" />
			</Svg>
		</View>
	)
}

export default LineChart
