import { ReactNode, useState } from "react"
import { Text, View } from "react-native"
import Svg, {
	Circle,
	G,
	Line,
	Polyline,
	Text as SVGText,
} from "react-native-svg"
import { computeDataPoints } from "../utils/linechart/compute-datapoints"
import {
	calculateGridValues,
	computeGrid,
} from "../utils/linechart/compute-grid"
import { calculateTicks } from "../utils/linechart/compute-linechart"
import { msToDate } from "../utils/linechart/helpers"
import { ChartGrid } from "./chart-grid"

export type LabelData = Record<string, string>

type LineChartProps = {
	data: { x: number | Date; y: number }[]
	tickCountTarget?: number // 2- 20,
	labelInterval?: number
	labelProp?: (
		label: LabelData,
		x: number,
		y: number,
		fontSize: number,
	) => React.ReactNode
}

const LineChart = ({
	data,
	tickCountTarget,
	labelInterval,
	labelProp,
}: LineChartProps) => {
	//TODO: Vertical, horizontal lines + full grid functionality
	// X and Y axis lines (optional)
	// Display X and Y axis values (optional)

	//How many X & Y lines to generate?
	//Lines are generated by spacing: roundUp((max value - min value) / array.length - 1)
	//Spacing is calculated by the chartWidth / aforementioned value and making the step value "nice" e.g. 5 or 10

	//Component height and width are determined by the parent container
	//The component fills the container
	//Size is determined by parent container flex and width values.
	const safeTickCountTarget = Math.min(Math.max(tickCountTarget ?? 3, 2), 20)
	const safeLabelInterval =
		labelInterval && labelInterval > 0 ? labelInterval : 1
	const [dimensions, setDimensions] = useState({ width: 0, height: 0 })

	const chartAxisValues = calculateGridValues(data)

	const xAxisVal = calculateTicks(
		safeTickCountTarget,
		chartAxisValues.minX,
		chartAxisValues.maxX,
		true,
		"week",
	)
	const yAxisVal = calculateTicks(
		safeTickCountTarget,
		chartAxisValues.minY,
		chartAxisValues.maxY,
		false,
	)

	const labelFontSize = (10 / 225) * dimensions.height
	const paddingX = (dimensions.width * 0.1 + labelFontSize) * 1.1
	const paddingY = (dimensions.height * 0.1 + labelFontSize) * 1.5

	const chartWidth = dimensions.width - paddingX * 2
	const chartHeight = dimensions.height - paddingY * 2

	const { xLineData, yLineData } = computeGrid(
		xAxisVal,
		yAxisVal,
		paddingX,
		paddingY,
		chartHeight,
		chartWidth,
		safeLabelInterval,
	)

	const dataPoints = computeDataPoints(
		data,
		paddingX,
		paddingY,
		chartWidth,
		chartHeight,
		xAxisVal,
		yAxisVal,
	)

	let polyLineStr = ""
	dataPoints.forEach((point, i) => {
		const x = point.cx
		const y = point.cy
		polyLineStr = polyLineStr + `${x},${y} `
	})

	return (
		<View
			style={{ flex: 1 }}
			onLayout={(e) => setDimensions(e.nativeEvent.layout)}
		>
			<Svg
				width={dimensions.width}
				height={dimensions.height}
				style={{ flex: 1 }}
			>
				<ChartGrid
					xLineData={xLineData}
					yLineData={yLineData}
					isDate={chartAxisValues.isDate}
					labelFontSize={labelFontSize}
					labelComponent={labelProp}
				/>
				<Line
					x1={paddingX}
					y1={paddingY + chartHeight}
					x2={paddingX + chartWidth}
					y2={paddingY + chartHeight}
					stroke="red"
				/>
				<SVGText
					x={paddingX - 15}
					y={paddingY + chartHeight}
					textAnchor={"middle"}
				>
					{yAxisVal.niceMin}
				</SVGText>
				<Line
					x1={paddingX}
					y1={paddingY}
					x2={paddingX + chartWidth}
					y2={paddingY}
					stroke="red"
				/>
				<SVGText x={paddingX - 15} y={paddingY} textAnchor={"middle"}>
					{yAxisVal.niceMax}
				</SVGText>

				<Line
					x1={paddingX}
					y1={paddingY}
					x2={paddingX}
					y2={paddingY + chartHeight}
					stroke="blue"
				/>
				<SVGText
					x={paddingX}
					y={paddingY + chartHeight + 15}
					textAnchor={"middle"}
					fontSize={10}
				>
					{msToDate(xAxisVal.niceMin, "day")}
				</SVGText>
				<Line
					x1={paddingX + chartWidth}
					y1={paddingY}
					x2={paddingX + chartWidth}
					y2={paddingY + chartHeight}
					stroke="blue"
				/>
				<SVGText
					x={paddingX + chartWidth}
					y={paddingY + chartHeight + 15}
					textAnchor={"middle"}
					fontSize={10}
					transform={`rotate(0,${paddingX + chartWidth}, ${paddingY + chartHeight + 15})`}
				>
					{msToDate(xAxisVal.niceMax, "day")}
				</SVGText>

				{dataPoints.map((point, i) => (
					<Circle cx={point.cx} cy={point.cy} key={i} r={2} />
				))}
				<Polyline points={polyLineStr} fill="none" stroke="black" />
			</Svg>
		</View>
	)
}

export default LineChart
