import { ReactNode, useState } from "react"
import { ColorValue, Text, View } from "react-native"
import Svg, {
	Circle,
	G,
	Line,
	Polyline,
	Rect,
	Text as SVGText,
} from "react-native-svg"
import { computeAxes } from "../utils/linechart/compute-axes"
import { computeDataPoints } from "../utils/linechart/compute-datapoints"
import {
	calculateGridValues,
	computeGrid,
} from "../utils/linechart/compute-grid"
import { calculateTicks } from "../utils/linechart/compute-linechart"
import { msToDate, toSvgX } from "../utils/linechart/helpers"
import { validateData } from "../utils/linechart/validate-data"
import { ChartAxes } from "./chart-axes"
import { ChartGrid } from "./chart-grid"
import { ToolTip } from "./chart-tooltip"
import DataPoint from "./data-point"

export type LabelData = Record<string, string>
type LineChartProps = {
	data: { x: number | Date; y: number }[]
	xTickCountTarget?: number // 2- 20,
	yTickCountTarget?: number // 2- 20,
	dateTickInterval?: "day" | "week" | "month" | "year"
	labelInterval?: number
	xAxisStroke?: ColorValue
	yAxisStroke?: ColorValue
	gridStroke?: ColorValue
	gridStrokeX?: ColorValue
	gridStrokeY?: ColorValue
	showGridX?: boolean
	showGridY?: boolean
	opacity?: string | number
	strokeWidth: number
	labelFont?: string
	showXLabels?: boolean
	showYLabels?: "left" | "right" | "none"
	showXAxis?: boolean
	showYAxis?: boolean
	dataPointFill?: string
	dataPointRadius?: number
	dataPointStroke?: ColorValue
	dataPointStrokeWidth: number
	showDatapoints: boolean
	lineStrokeWidth?: number
	lineStroke?: string
	toolTipTitle: string
	toolTipValueLabel: string
	toolTipFontSize?: number
	toolTipTitleFont?: string
	accessibilityLabel: string
	labelProp?: (
		label: LabelData,
		x: number,
		y: number,
		fontSize: number,
	) => React.ReactNode
}

/**
 *
 * @param TickCountTarget Number of ticks the chart tries to generate on the axis (does not work with dates)
 *
 */
const LineChart = ({
	data,
	xTickCountTarget,
	yTickCountTarget,
	dateTickInterval,
	labelInterval,
	xAxisStroke,
	yAxisStroke,
	gridStroke,
	gridStrokeX,
	gridStrokeY,
	showGridX,
	showGridY,
	opacity,
	strokeWidth,
	labelFont,
	showXLabels,
	showYLabels,
	showXAxis,
	showYAxis,
	dataPointFill,
	dataPointRadius,
	dataPointStroke,
	dataPointStrokeWidth,
	showDatapoints,
	lineStrokeWidth,
	lineStroke,
	toolTipTitle,
	toolTipValueLabel,
	toolTipFontSize,
	toolTipTitleFont,
	accessibilityLabel,
	labelProp,
}: LineChartProps) => {
	//TODO: Vertical, horizontal lines + full grid functionality
	// X and Y axis lines (optional)
	// Display X and Y axis values (optional)

	//How many X & Y lines to generate?
	//Lines are generated by spacing: roundUp((max value - min value) / array.length - 1)
	//Spacing is calculated by the chartWidth / aforementioned value and making the step value "nice" e.g. 5 or 10

	//Component height and width are determined by the parent container
	//The component fills the container
	//Size is determined by parent container flex and width values.

	const [dimensions, setDimensions] = useState({ width: 0, height: 0 })
	const [selectedDataPoint, setSelectedDataPoint] = useState<null | {
		cx: number
		cy: number
		x: number
		y: number
	}>(null)

	if (dimensions.height === 0 || dimensions.width === 0) {
		return (
			<View
				style={{ flex: 1 }}
				onLayout={(e) => setDimensions(e.nativeEvent.layout)}
			/>
		)
	}
	const validatedData = validateData(data)
	if (validatedData === null) {
		return null
	}
	const { sortedInputArr, hasDates } = validatedData
	const safeTickCountTargetX = Math.min(Math.max(xTickCountTarget ?? 3, 2), 20)
	const safeTickCountTargetY = Math.min(Math.max(yTickCountTarget ?? 3, 2), 20)
	const chartAxisValues = calculateGridValues(data)
	const safeGridStroke = gridStroke ?? "black"
	const safeXAxisStroke = xAxisStroke ?? safeGridStroke
	const safeYAxisStroke = yAxisStroke ?? safeGridStroke

	const safeOpacity = opacity ?? "100%"
	const safeStrokeWidth = strokeWidth ?? 10
	const safeLineStrokeWidth = lineStrokeWidth ?? 10
	const safeShowXLabel = showXLabels !== false
	const safeYLabelPos = showYLabels ?? "left"

	const safeLabelInterval =
		labelInterval && labelInterval > 0 ? labelInterval : 1
	const safeDateTickInterval = dateTickInterval ?? "week"
	const safeShowXAxis = showXAxis ?? true
	const safeShowYAxis = showYAxis ?? true

	const safeShowGridX = showGridX ?? true
	const safeShowGridY = showGridY ?? true

	//Datapoint props
	const safeDataPointFill = dataPointFill ?? "black"
	const safeDataPointRadius = dataPointRadius ?? 2
	const safeDataPointStroke = dataPointStroke ?? "black"
	const safeDataPointStrokeWidth = dataPointStrokeWidth ?? 1
	const safeShowDataPoints = showDatapoints ?? true

	const xAxisVal = calculateTicks(
		safeTickCountTargetX,
		chartAxisValues.minX,
		chartAxisValues.maxX,
		chartAxisValues.isDate,
		safeDateTickInterval,
	)
	const yAxisVal = calculateTicks(
		safeTickCountTargetY,
		chartAxisValues.minY,
		chartAxisValues.maxY,
		false,
	)

	const labelFontSize = (10 / 225) * dimensions.height
	const scalableToolTipFontSize =
		toolTipFontSize ?? 1 * (10 / 225) * dimensions.height
	const scalableStrokeWidth =
		(safeStrokeWidth / 1000) *
		(dimensions.height - (dimensions.height * 0.1 + labelFontSize) * 1.5)
	const scalableLineStrokeWidth =
		(safeLineStrokeWidth / 1000) *
		(dimensions.height - (dimensions.height * 0.1 + labelFontSize) * 1.5)
	const paddingX = (dimensions.width * 0.1 + labelFontSize) * 1.1
	const paddingY = (dimensions.height * 0.1 + labelFontSize) * 1.5
	const chartWidth = dimensions.width - paddingX * 2
	const chartHeight = dimensions.height - paddingY * 2

	const bottomLabelSpacing = chartWidth * 0.111
	const scalableRadius = safeDataPointRadius * chartHeight * 0.05
	const scalableDataPointStrokeWidth =
		safeDataPointStrokeWidth * (scalableRadius / 10)
	//TODO: Change to xGridData and yGridData
	const { xLineData, yLineData } = computeGrid(
		xAxisVal,
		yAxisVal,
		paddingX,
		paddingY,
		chartHeight,
		chartWidth,
		safeLabelInterval,
		labelFontSize,
		safeShowXLabel,
		safeYLabelPos,
		bottomLabelSpacing,
	)

	const { xAxisData, yAxisData, bottomLabelData, topLabelData } = computeAxes(
		xAxisVal,
		yAxisVal,
		paddingX,
		paddingY,
		chartHeight,
		chartWidth,
		labelFontSize,
		safeShowXLabel,
		safeYLabelPos,
		safeShowXAxis,
		safeShowYAxis,
		bottomLabelSpacing,
	)

	const dataPoints = computeDataPoints(
		sortedInputArr,
		paddingX,
		paddingY,
		chartWidth,
		chartHeight,
		xAxisVal,
		yAxisVal,
		bottomLabelSpacing,
	)

	let polyLineStr = ""
	dataPoints.forEach((point, i) => {
		if (i === 0) {
			polyLineStr = `${point.cx - bottomLabelSpacing / 1.5} ${point.cy} `
		}
		const x = point.cx
		const y = point.cy
		polyLineStr = polyLineStr + `${x},${y} `
	})
	console.log("label", accessibilityLabel)

	return (
		<View
			style={{ flex: 1 }}
			onLayout={(e) => setDimensions(e.nativeEvent.layout)}
			accessibilityRole="image"
			accessibilityLabel={accessibilityLabel}
		>
			<Svg
				width={dimensions.width}
				height={dimensions.height}
				style={{ flex: 1 }}
			>
				<ChartGrid
					xLineData={xLineData}
					yLineData={yLineData}
					isDate={chartAxisValues.isDate}
					labelFontSize={labelFontSize}
					labelComponent={labelProp}
					stroke={safeGridStroke}
					xStroke={gridStrokeX}
					yStroke={gridStrokeY}
					strokeWidth={scalableStrokeWidth}
					opacity={safeOpacity}
					showGridX={safeShowGridX}
					showGridY={safeShowGridY}
					labelFont={labelFont}
				/>
				<ChartAxes
					paddingX={paddingX}
					paddingY={paddingY}
					chartHeight={chartHeight}
					chartWidth={chartWidth}
					xAxisData={xAxisData}
					yAxisData={yAxisData}
					fontSize={labelFontSize}
					hasDates={hasDates}
					strokeWidth={scalableStrokeWidth}
					opacity={safeOpacity}
					labelComponent={labelProp}
					xAxisStroke={safeXAxisStroke}
					yAxisStroke={safeYAxisStroke}
					bottomLabelData={bottomLabelData}
					topLabelData={topLabelData}
					labelFont={labelFont}
				/>

				<Polyline
					points={polyLineStr}
					fill="none"
					stroke={lineStroke ?? "black"}
					strokeWidth={scalableLineStrokeWidth}
				/>
				<Rect
					width={dimensions.width}
					height={dimensions.height}
					fill={"transparent"}
					onPress={() => {
						if (selectedDataPoint) {
							setSelectedDataPoint(null)
						}
					}}
				/>
				{dataPoints.map((point, i) => (
					<>
						<DataPoint
							cx={point.cx}
							cy={point.cy}
							fill={safeDataPointFill}
							radius={scalableRadius}
							stroke={safeDataPointStroke}
							strokeWidth={scalableDataPointStrokeWidth}
							isVisible={safeShowDataPoints}
							onPress={() =>
								setSelectedDataPoint({
									cx: point.cx,
									cy: point.cy,
									x: point.x,
									y: point.y,
								})
							}
						/>
					</>
				))}
				{selectedDataPoint && (
					<ToolTip
						data={selectedDataPoint}
						chartHeight={chartHeight}
						chartWidth={chartWidth}
						dataPointRadius={scalableRadius}
						labelFont={labelFont}
						fontSize={scalableToolTipFontSize}
						toolTipTitleFont={toolTipTitleFont}
						toolTipTitle={toolTipTitle}
						toolTipValueLabel={toolTipValueLabel}
					/>
				)}
			</Svg>
		</View>
	)
}

export default LineChart
